import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProviderGate } from "@/components/app/clerk-provider-gate";
import { agentLaunchBootstrapScript } from "@/lib/agent-launch-bootstrap";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Dark only — keeps native UI (scrollbars, form controls) from rendering light.
export const viewport: Viewport = {
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          id="agent-launch-fragment-bootstrap"
          // This constant script must execute while the document is parsed;
          // Next's Script loader defers inline content until its runtime loads.
          dangerouslySetInnerHTML={{ __html: agentLaunchBootstrapScript() }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <ClerkProviderGate>{children}</ClerkProviderGate>
      </body>
    </html>
  );
}
